### PR TITLE
Python3 compatability

### PR DESCRIPTION
**Pull request by dschaller**

### CODE REVIEW

**Comment by dschaller** [comment]
@amitu mind taking a look over this? :D

**Comment by amitu** [comment]
Needs more work :-p

**Comment by dschaller** [comment]
@amitu alright all updated for python3 with some lint fixes as well :)

**Comment by amitu** [comment]
@dschaller, thanks a lot for the pull request. 

I am no longer using Browserstack in any serious way, so hard for me to test. Do you want ownership of this project?

**Comment by dschaller** [comment]
@amitu sure :)

**Comment by amitu** [comment]
Cool. I have added you as a collaborator. You are free to merge this pull request after you are satisfied. If you want to move over the development to your fork, please update the README here pointing to your fork instead.

Drop me a mail when you are ready to publish a new release on pypi.

**Comment by amitu** [comment]
Hey @dschaller, please coordinate with @nakula. He is also working on some enhancements to this package, and they may be moving the development elsewhere.

**Pull request merged**
